#!/usr/bin/env node
# comment
var debug = require('debug')('DiskSite');
var app = require('../app');

app.set('port', process.env.PORT || 3000);

var server = app.listen(app.get('port'), function() {
    debug('Express server listening on port ' + server.address().port);
});
